### ISSUE TITLE
TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by dweinstein** [nowsecure/ipa-extract-exec#1]
```
/Users/user/.nvm/versions/node/v5.10.0/lib/node_modules/ipa-extract-exec/bin.js:14
  if (err) { throw err }
             ^

TypeError: Cannot read property 'length' of undefined
    at Parser.parseHead (/Users/user/.nvm/versions/node/v5.10.0/lib/node_modules/ipa-extract-exec/node_modules/macho/lib/macho/parser.js:35:10)
    at Parser.execute (/Users/user/.nvm/versions/node/v5.10.0/lib/node_modules/ipa-extract-exec/node_modules/macho/lib/macho/parser.js:14:18)
    at Object.parse (/Users/user/.nvm/versions/node/v5.10.0/lib/node_modules/ipa-extract-exec/node_modules/macho/lib/macho.js:7:29)
    at isEncryptedSync (/Users/user/.nvm/versions/node/v5.10.0/lib/node_modules/ipa-extract-exec/is-encrypted-sync.js:17:24)
    at AssertByteCountStream.<anonymous> (/Users/user/.nvm/versions/node/v5.10.0/lib/node_modules/ipa-extract-exec/index.js:43:54)
    at emitNone (events.js:85:20)
    at AssertByteCountStream.emit (events.js:179:7)
    at endReadableNT (_stream_readable.js:913:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

```

**Comment by dweinstein** [comment]
seems to be related to a non-fat macho
